# Global configs
http://localhost:3000
Accept: application/json
--

##################### Team's APIs ##################### 

# list all teams
--
GET /teams

--
# create a new team
POST /teams
{
  "name": "team 1",
  "department": "5fe60630e9c0d8faf34d0956"
}

--
# update one department by id
PATCH /teams/5fe60630e9c0d8faf34d0956
{
	"name": "new name"
}

# get one department id
--
GET /teams/5fe60630e9c0d8faf34d0956

--
# delete a team
DELETE /teams/5fe604be6da65eeb28471d98

##################### Department's APIs ###############

# list all departments
--
GET /departments

--
# create a new department
POST /departments
{
  "name": "dept 2"
}

--
# update one department by id
PATCH /departments/5fe60630e9c0d8faf34d0956
{
	"name": "new name"
}

# get one department id
--
GET /departments/5fe60630e9c0d8faf34d0956

--
# delete a department
DELETE /departments/5fe604be6da65eeb28471d98

##################### Employee's APIs #################

# list all employees
--
GET /employees

--
# get one employee by id
GET /employees/5fe6f19af4768c25ca479514

--
# create a new employee
POST /employees
{
	"username": "dungtd12",
	"password": "123",
	"role": "member"
}

--
# update one employee by id
PATCH /employees/5fe6f19af4768c25ca479514
{
	"role": "member"
}

--
# delete one employee by id
DELETE /employees/5fe6f19af4768c25ca479514
